import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navBar";
import Banner from "../components/Banner";
import { client, urlFor } from "../utils/Client";
import { MdAddShoppingCart } from "react-icons/md";
import { useSelector, useDispatch } from "react-redux";
import FooterBanner from "../components/FooterBanner";
import ProductCard from "../components/ProductCard";
import Cart from "../components/Cart";
import EmaiSub from "../components/EmaiSub";
export default function Home({ products }) {
  return (
    <div className="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Banner />
      <section className="my-6 max-w-3xl w-[80%]   grid  md:grid-cols-2 lg:grid-cols-3 gap-4 mx-auto ">
        {products?.map((p) => {
          return <ProductCard p={p} key={p._id} />;
        })}
      </section>
      <FooterBanner />
      <EmaiSub />
    </div>
  );
}

export async function getStaticProps() {
  try {
    const products = await client.fetch(`*[_type == "product"]`);
    // console.log(products);
    return {
      props: {
        products,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
